export const seedPhrases = [
  "Super mario",
  "Moon",
  "Juragan",
  "Kopi at midnight",
  "Aku capek but still okay",
  "Langit jam 2 pagi",
  "Small win hari ini",
  "Bulan tapi noise",
  "Nostalgia aneh",
  "Late night warteg",
  "Pixel memory",
  "Kepala penuh static",
  "Sunset tapi chaos",
  "Nasi goreng and broken focus",
  "Silent mode hati",
  "Aku vs overthinking",
  "Dream kecil",
  "Coffee and regret lite",
  "Planet kosan",
  "Midnight bengong",
  "Lucu tapi kosong",
  "Fake calm",
  "Langit ungu",
  "Random memory unlocked",
  "Hujan plus deadline",
  "Sabar mode on",
  "Juragan moonlight",
  "Super mario tapi galau",
  "Notebook and chaos",
  "Shadow di pojok kamar",
  "Ramen dan anxiety mini",
  "Calm tapi bohong",
  "Lupa tapi inget",
  "Kursi plastik philosophy",
  "Sore low battery",
  "Bengong premium",
  "Tiny chaos",
  "Mie malam dan ide jelek",
  "Neon hujan",
  "Moon over warteg",
  "Kopi, hujan, repeat",
  "Saturn di kepala",
  "Hati airplane mode",
  "Receh but real",
  "Kasur dan existential crisis",
  "Waktu ngaret",
  "Dream tapi pending",
  "Pixel nostalgia",
  "Juragan of sadness",
  "Telegram but poetic"
];
